# Generated by Django 4.2.8 on 2024-01-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_parent'),
        ('categories', '0006_alter_category_hashtag_name_alter_category_head_name_and_more'),
    ]

    operations = [
    ]
