# Generated by Django 4.2.8 on 2024-01-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_merge_20240118_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hashtag_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='head_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
