# Generated by Django 4.2.8 on 2024-01-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
