stages:
  - build

build-job:
  stage: build
  only:
    - main
  
  tags:
    - mane
   
  script:
    - cd /home/mane_project/mane
    - pwd
    - whoami
    - git checkout main || fail
    - git reset --hard origin/main || fail
    - git pull origin main || fail
    - docker compose -f docker-compose.prod.yml up --build -d

