# Generated by Django 4.2.8 on 2024-01-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_prepare_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gif',
            field=models.FileField(null=True, upload_to='product/gif/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prepare_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
