# Generated by Django 4.2.8 on 2024-01-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(default=1, upload_to='banners/video'),
            preserve_default=False,
        ),
    ]
