# Generated by Django 4.2.8 on 2024-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(null=True, upload_to='banners/video'),
        ),
    ]
