# Generated by Django 4.2.8 on 2024-01-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
    ]
