# Generated by Django 4.2.8 on 2024-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_description_en_remove_product_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='summary_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='summary_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
