# Generated by Django 4.2.8 on 2024-01-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_banner_body_ru_banner_body_uz_banner_summary_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/banner'),
        ),
    ]
