# Generated by Django 4.2.8 on 2024-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maydons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maydon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('rasmlari', models.ImageField(upload_to='maydonlar/')),
                ('bron_qilish_narxi', models.FloatField()),
                ('uzunlik', models.FloatField()),
                ('enlik', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
